name: Run commitlint
concurrency:
  group: ci-${{ github.ref }}-commitlint
  cancel-in-progress: true

on:
  pull_request:
    types: [edited, synchronize, opened, reopened]
    branches:
      - main

jobs:
  lint-commit-message:
    name: Lint commit message
    runs-on: ubuntu-latest
    steps:
      - uses: ahmadnassri/action-commit-lint@v1
